export enum ItineraryItemStyle {
    CheckIn = 'Check-In',
    FlightArrival = 'FlightArrival',
    FlightDeparture = 'FlightDeparture',
    Accommodation = 'Accommodation',
    Snippet = 'Snippet',
    Transfer = 'Transfer',
    Location = 'Location',
    Anchor = 'Anchor',
    Sail = 'SaiFl',
    Dates = 'dates-icon',
    Debark = 'debark-icon',
    Embark = 'embark-icon',
    Fares = 'fares-icon',
    NumberOfNights = 'number-of-nights-icon',
    Vessel = 'vessel-icon',
}